name: Test Execution - Playwright
run-name: ${{inputs.env}} - playwright test execution

on:
  workflow_dispatch:
    inputs:
      env:
        description: Select Test Environment
        type: choice
        default: staging
        options:
          - staging
          - prod

env:
  TESTENV: ${{inputs.env}}
  DOCKER_COMPOSE_FILE: rolevault-webapp/docker-compose.${{ inputs.env }}.yml  # Global for all steps

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout Test Repo
      uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Checkout RoleVault Webapp Repo
      uses: actions/checkout@v4
      with:
        repository: NayeemJohnY/rolevault-webapp
        path: rolevault-webapp

    - name: Start RoleVault Webapp (Docker Compose Up)
      run: docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d

    - name: Wait for RoleVault to start
      run: |
        for i in {1..60}; do
          if docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} logs | grep -q "RoleVault started successfully!"; then
            echo "RoleVault started successfully!"
            docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} logs --tail 50
            exit 0
          fi
          sleep 5
        done
        echo "Timeout: RoleVault did not start within 5 minutes"
        docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} logs --tail 50
        exit 1

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Stop RoleVault Webapp (Docker Compose Down)
      if: always()
      run: docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} down

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
